// Suggested code may be subject to a license. Learn more: ~LicenseLog:4178335187.
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'E-Library',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
        <body>
            {children}
        </body>
    </html>
  )
}
